# Generated by Django 5.1.1 on 2024-10-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_bloggers_blog_published_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggers',
            name='password',
            field=models.CharField(editable=False, max_length=3000),
        ),
        migrations.AlterField(
            model_name='bloggers',
            name='profile_pic',
            field=models.ImageField(default='bloggers_profiles/default.jpg', null=True, upload_to='bloggers_profiles'),
        ),
    ]
